### PR TITLE
Manage network dns settings properly

### PR DESCRIPTION
**Pull request by erikh**
This change enables the creation and management of DNS settings through
terraform.

There are still some serious issues with how this is tested, and there
may be unseen problems here. A separate issue should be created to
manage this problem.

Signed-off-by: Erik Hollensbe <linux@hollensbe.org>

### CODE REVIEW

**Comment by erikh** [comment]
@someara please test this manually before performing any merge. I am a little worried more work needs to be done here, but I have a less comprehensive way to test it than you do.

**Comment by craSH** [comment]
For outside folks, are there any documents about how to setup a dev environment so we could test this before release as well? I'd be happy to if I knew how to build the go code and locally use it in a TF project, etc.

**Comment by someara** [comment]
Hello!

I manually fetched this PR to my laptop and added the example from testdata to the examples/

https://github.com/zerotier/terraform-provider-zerotier/commit/a44370ef6c0b8a9a184dbd9e05df0deac965560b

Then I built the provider (make), made sure it was in my local cache as 0.2.0, then ran "terraform apply" against my personal Central account from the examples directory.

It did not populate the DNS settings for leisure.town 

Screenshot 2021-10-25 at 14 28 22

Unsure why exactly.... there were no errors. It just silently failed

-s

**Comment by erikh** [comment]
Hmm. Damnit.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by erikh** [comment]
@craSH my apologies for taking so much time to get back to you on this. I'll make a note to revise the readme with any additional documentation that needs to occur.

**Pull request merged**
